language: cpp
compiler: gcc
os: linux

addons:
  apt:
    packages:
    - cmake
    - casacore-dev
    - libgsl-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-test-dev

script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && make && make check
